apiVersion: v1
kind: ReplicationController
metadata: 
     name: myapp-rc
spec: 
    replicas: 3
    selector:
        app: myapp
    template:
        metadata:
          labels: 
             app: myapp
        spec: 
         containers:
            - name: myapp-container
              image: nvrk1972/myjavaapp31dec24:1
              ports:
              - containerPort: 8080	                