apiVersion: v1
kind: ReplicationController
metadata: 
     name: myapp-rc
spec: 
    replicas: 3
    selector:
        app: myapp
        version: 2.6.1
    template:
        metadata:
          labels: 
             app: myapp
             version: 2.6.1
        spec: 
         containers:
            - name: myapp-container
              image: maha4iac/mahaLogin:1
              ports:
              - containerPort: 8080	                