apiVersion: v1
kind: ReplictionController
metadata: 
     name: myapp-rc
spec: 
    replicas: 5
    selectors: 
        app: myapp
    template:
        metadata:
        labels: 
            app: myapp
        spec: 
         containers:
            - name: myapp-container
              image: maha4iac/mahalogin:1
              ports:
              - containerPort: 8080	                